import { type Oferta } from './types'

export const SEED_OFERTAS: Omit<Oferta, 'pais'>[] = [
  {
    "id": "27f2ceb3-fb95-45cd-ae20-251453af51a0",
    "nro": 2,
    "consecutivo": "PR-00002",
    "proyecto": "Edificio Multifamiliar — 5 pisos (40 aptos)",
    "fecha_emision": "2026-07-12",
    "moneda": "Soles",
    "margen_general": 15,
    "pct_impuesto": 0,
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "observaciones": "Presupuesto base tomado del documento \"Sistema Ofertas Ingeniería\" (Anexo 11.4) y ampliado con partidas propias de un edificio multifamiliar. Valores convertidos de COP a Soles (1 Sol = 1.000 COP). Incluye mano de obra, materiales y equipos según el alcance.",
    "renglones": [
      {
        "id": "814ef9d7-ad63-46c9-955a-a6f8f0d87b7f",
        "tipo": "T1",
        "codigo": "1",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-01 · ESTUDIOS, DISEÑOS, LICENCIAS Y PÓLIZAS",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "3e802d26-0819-436b-bd8f-34ede731c0ff",
        "tipo": "D2",
        "codigo": "1.01",
        "concepto": "MOI",
        "ref_id": "",
        "descripcion": "Dirección de preconstrucción y coordinación de diseños",
        "unidad": "mes",
        "cantidad": 3,
        "costo_unitario": 8750,
        "margen": 15
      },
      {
        "id": "4f3deda3-1024-4cfb-9a15-0e1ef167d18e",
        "tipo": "D5",
        "codigo": "1.02",
        "concepto": "Subcontrato",
        "ref_id": "",
        "descripcion": "Subcontrato: Estudio de suelos y geotecnia",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 20160,
        "margen": 15
      },
      {
        "id": "4575a364-6c56-4dc5-9c76-b69d762b3e8d",
        "tipo": "D5",
        "codigo": "1.03",
        "concepto": "Subcontrato",
        "ref_id": "",
        "descripcion": "Subcontrato: Diseños estructural, hidrosanitario y eléctrico",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 106400,
        "margen": 15
      },
      {
        "id": "a0ff7de6-0668-41c8-a0a1-dc9472580896",
        "tipo": "D6",
        "codigo": "1.04",
        "concepto": "Otro",
        "ref_id": "",
        "descripcion": "Licencia de construcción y curaduría urbana",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 93500,
        "margen": 15
      },
      {
        "id": "1fd0fa05-62b1-4805-b338-e6d6617ff00a",
        "tipo": "D6",
        "codigo": "1.05",
        "concepto": "Otro",
        "ref_id": "",
        "descripcion": "Pólizas: cumplimiento, estabilidad y RCE",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 46200,
        "margen": 15
      },
      {
        "id": "b7d5b287-f636-464b-94a6-c2a572456962",
        "tipo": "T1",
        "codigo": "2",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-02 · OBRAS PRELIMINARES Y LIMPIEZA DEL TERRENO",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "1e66e76e-e1d2-4fe8-afbb-1859aeb73a41",
        "tipo": "D1",
        "codigo": "2.01",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla de limpieza, desmonte y descapote",
        "unidad": "día",
        "cantidad": 40,
        "costo_unitario": 416,
        "margen": 15
      },
      {
        "id": "9985e004-3c37-4914-9ba6-b61b76bcc39c",
        "tipo": "D1",
        "codigo": "2.02",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Trazado y replanteo topográfico",
        "unidad": "día",
        "cantidad": 12,
        "costo_unitario": 486.4,
        "margen": 15
      },
      {
        "id": "26be6671-aeff-4fb5-a094-3464bc067bc1",
        "tipo": "D2",
        "codigo": "2.03",
        "concepto": "MOI",
        "ref_id": "",
        "descripcion": "Residente de obra (dirección técnica)",
        "unidad": "mes",
        "cantidad": 10,
        "costo_unitario": 8450,
        "margen": 15
      },
      {
        "id": "cdebaa39-5e4f-4e36-b72f-1ede05129bb2",
        "tipo": "D2",
        "codigo": "2.04",
        "concepto": "MOI",
        "ref_id": "",
        "descripcion": "Maestro general de obra",
        "unidad": "mes",
        "cantidad": 10,
        "costo_unitario": 4940,
        "margen": 15
      },
      {
        "id": "35f16f13-ae0b-41c4-8086-6e4c28e79e22",
        "tipo": "D3",
        "codigo": "2.05",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Cerramiento provisional en tela verde + postes",
        "unidad": "ml",
        "cantidad": 180,
        "costo_unitario": 38.4,
        "margen": 15
      },
      {
        "id": "5018d92b-3d65-4e76-b073-3d0beec89145",
        "tipo": "D3",
        "codigo": "2.06",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Caseta / almacén provisional de obra",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 10030,
        "margen": 15
      },
      {
        "id": "02e64a31-4dee-4c21-a49b-a8462d35f04d",
        "tipo": "D4",
        "codigo": "2.07",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Alquiler generador eléctrico de obra",
        "unidad": "mes",
        "cantidad": 10,
        "costo_unitario": 3776,
        "margen": 15
      },
      {
        "id": "af33a80a-f63e-4946-bbeb-2c1194a3f065",
        "tipo": "T1",
        "codigo": "3",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-03 · MOVIMIENTO DE TIERRAS Y EXCAVACIÓN",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "b91e5ddd-d913-4103-b1ec-312193330557",
        "tipo": "D1",
        "codigo": "3.01",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla de excavación y perfilado",
        "unidad": "día",
        "cantidad": 60,
        "costo_unitario": 442,
        "margen": 15
      },
      {
        "id": "62745001-cfa4-4400-b254-9fba40de7a53",
        "tipo": "D2",
        "codigo": "3.02",
        "concepto": "MOI",
        "ref_id": "",
        "descripcion": "Comisión topográfica de control",
        "unidad": "mes",
        "cantidad": 6,
        "costo_unitario": 5460,
        "margen": 15
      },
      {
        "id": "93fb4b9a-2a90-4380-8b31-57a703265c6b",
        "tipo": "D3",
        "codigo": "3.03",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Alquiler volqueta retiro de material (viaje)",
        "unidad": "vje",
        "cantidad": 90,
        "costo_unitario": 212.4,
        "margen": 15
      },
      {
        "id": "05079553-9270-4cb0-9783-1c99bf5b3068",
        "tipo": "D4",
        "codigo": "3.04",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Alquiler retroexcavadora (hora-máquina)",
        "unidad": "h",
        "cantidad": 120,
        "costo_unitario": 171.1,
        "margen": 15
      },
      {
        "id": "32bd65d8-2458-4a03-b502-388efc7c0cca",
        "tipo": "D4",
        "codigo": "3.05",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Compresor + martillo neumático (perforación)",
        "unidad": "día",
        "cantidad": 30,
        "costo_unitario": 330.4,
        "margen": 15
      },
      {
        "id": "d0837dd3-e70a-4131-82f0-830b04640408",
        "tipo": "T1",
        "codigo": "4",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-04 · CIMENTACIÓN Y CONTENCIÓN",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "cde8a9d2-d9c6-492b-8872-901c559a90e1",
        "tipo": "D1",
        "codigo": "4.01",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla armado de acero y fundida",
        "unidad": "día",
        "cantidad": 90,
        "costo_unitario": 468,
        "margen": 15
      },
      {
        "id": "20b8d699-1ff7-45f1-909c-304c4cf29046",
        "tipo": "D2",
        "codigo": "4.02",
        "concepto": "MOI",
        "ref_id": "",
        "descripcion": "Ingeniero de calidad / interventoría interna",
        "unidad": "mes",
        "cantidad": 10,
        "costo_unitario": 6760,
        "margen": 15
      },
      {
        "id": "224cccda-a9c4-42a1-8076-6d8eeb7e89f2",
        "tipo": "D3",
        "codigo": "4.03",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Concreto premezclado 3.000 psi",
        "unidad": "m³",
        "cantidad": 320,
        "costo_unitario": 624,
        "margen": 15
      },
      {
        "id": "a059294b-96ba-4658-841b-fff781dad4d3",
        "tipo": "D3",
        "codigo": "4.04",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Acero de refuerzo 60.000 psi",
        "unidad": "kg",
        "cantidad": 38000,
        "costo_unitario": 6.136,
        "margen": 15
      },
      {
        "id": "45de35e6-dc28-4356-bd1f-7294fefc6dad",
        "tipo": "D3",
        "codigo": "4.05",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Malla electrosoldada",
        "unidad": "m²",
        "cantidad": 850,
        "costo_unitario": 21.6,
        "margen": 15
      },
      {
        "id": "56a3d44e-935e-44e1-a839-6ca8df9f1817",
        "tipo": "D4",
        "codigo": "4.06",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Taladro perforador roto-percutor (anclajes / pernos)",
        "unidad": "día",
        "cantidad": 45,
        "costo_unitario": 114,
        "margen": 15
      },
      {
        "id": "09c5f5d5-bc17-46ee-9727-66715a5befec",
        "tipo": "D4",
        "codigo": "4.07",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Equipo de perforación pilotes / micropilotes",
        "unidad": "día",
        "cantidad": 20,
        "costo_unitario": 1416,
        "margen": 15
      },
      {
        "id": "0f79e98a-766e-41ae-bc38-1150631105c3",
        "tipo": "T1",
        "codigo": "5",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-05 · ESTRUCTURA EN CONCRETO",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "0821529f-c448-4c11-8044-f33fcfe54971",
        "tipo": "D1",
        "codigo": "5.01",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla estructura (columnas, vigas, placas)",
        "unidad": "día",
        "cantidad": 220,
        "costo_unitario": 475.2,
        "margen": 15
      },
      {
        "id": "73514fa6-6b63-4fc6-97d0-8f27a5b5d68d",
        "tipo": "D3",
        "codigo": "5.02",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Concreto premezclado 4.000 psi",
        "unidad": "m³",
        "cantidad": 540,
        "costo_unitario": 672,
        "margen": 15
      },
      {
        "id": "8ca1a41b-b91a-4cb1-bbf4-dfbc378febda",
        "tipo": "D3",
        "codigo": "5.03",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Acero de refuerzo figurado",
        "unidad": "kg",
        "cantidad": 62000,
        "costo_unitario": 6.254,
        "margen": 15
      },
      {
        "id": "e03f60a7-bc02-4f6d-8e25-3aa330dccb83",
        "tipo": "D3",
        "codigo": "5.04",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Formaleta metálica (alquiler m²-mes)",
        "unidad": "m²",
        "cantidad": 1600,
        "costo_unitario": 25.96,
        "margen": 15
      },
      {
        "id": "9ce71d01-2411-4a5d-9c37-e00e2aa8e857",
        "tipo": "D3",
        "codigo": "5.05",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Casetón / aligerante de placa",
        "unidad": "un",
        "cantidad": 4200,
        "costo_unitario": 11.4,
        "margen": 15
      },
      {
        "id": "1e53c1f7-f566-4e9c-b2f0-4a88e5eb56ac",
        "tipo": "D4",
        "codigo": "5.06",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Vibrador de concreto de inmersión",
        "unidad": "día",
        "cantidad": 110,
        "costo_unitario": 66,
        "margen": 15
      },
      {
        "id": "3f5e7389-82d2-44d1-b717-61f374fad242",
        "tipo": "D4",
        "codigo": "5.07",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Bombeo de concreto (hora-equipo)",
        "unidad": "h",
        "cantidad": 180,
        "costo_unitario": 377.6,
        "margen": 15
      },
      {
        "id": "46dcad5b-83aa-4fd5-bb6c-57b4a5442c18",
        "tipo": "D4",
        "codigo": "5.08",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Taladro industrial + cortadora / pulidora",
        "unidad": "día",
        "cantidad": 90,
        "costo_unitario": 72,
        "margen": 15
      },
      {
        "id": "472b272d-6d19-4a17-9890-cb154326846d",
        "tipo": "T1",
        "codigo": "6",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-06 · MAMPOSTERÍA Y CERRAMIENTOS",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "3a04a982-debf-4106-ac19-a1b03fc2eecb",
        "tipo": "D1",
        "codigo": "6.01",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla de mampostería",
        "unidad": "día",
        "cantidad": 160,
        "costo_unitario": 429,
        "margen": 15
      },
      {
        "id": "98e13356-38aa-413e-838e-393f6e206fef",
        "tipo": "D3",
        "codigo": "6.02",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Ladrillo tolete estructural",
        "unidad": "un",
        "cantidad": 185000,
        "costo_unitario": 1.14,
        "margen": 15
      },
      {
        "id": "93ceffe5-5b5e-4b25-8d00-55c82ffe4b63",
        "tipo": "D3",
        "codigo": "6.03",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Mortero de pega (cemento + arena)",
        "unidad": "m³",
        "cantidad": 220,
        "costo_unitario": 408,
        "margen": 15
      },
      {
        "id": "85b2c3f7-8899-4a0d-9fd5-861b44854bdf",
        "tipo": "D4",
        "codigo": "6.04",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Taladro percutor para mampostería",
        "unidad": "día",
        "cantidad": 60,
        "costo_unitario": 54,
        "margen": 15
      },
      {
        "id": "cd800050-5c41-4db0-a171-b4de983c38d4",
        "tipo": "T1",
        "codigo": "7",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-07 · PAÑETES, REVOQUES Y CIELOS RASOS",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "ef902ab7-83f9-4bf9-b492-f3735e08e90c",
        "tipo": "D1",
        "codigo": "7.01",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla de pañete y revoque",
        "unidad": "día",
        "cantidad": 150,
        "costo_unitario": 429,
        "margen": 15
      },
      {
        "id": "19854213-0b5f-45be-bf21-22978bab8c30",
        "tipo": "D1",
        "codigo": "7.02",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla de cielo raso en drywall",
        "unidad": "día",
        "cantidad": 90,
        "costo_unitario": 442,
        "margen": 15
      },
      {
        "id": "e92117fb-e7b7-44df-9e3b-2d95177c122c",
        "tipo": "D3",
        "codigo": "7.03",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Mortero de pañete (cemento + arena)",
        "unidad": "m³",
        "cantidad": 180,
        "costo_unitario": 408,
        "margen": 15
      },
      {
        "id": "cbccbdfe-ce73-47e3-91be-06df96767995",
        "tipo": "D3",
        "codigo": "7.04",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Lámina drywall + estructura + masilla",
        "unidad": "m²",
        "cantidad": 2400,
        "costo_unitario": 46.36,
        "margen": 15
      },
      {
        "id": "a7ad67b2-6046-4d3c-a91f-42e763090624",
        "tipo": "D4",
        "codigo": "7.05",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Mezcladora de mortero",
        "unidad": "día",
        "cantidad": 90,
        "costo_unitario": 48,
        "margen": 15
      },
      {
        "id": "7f14196f-6fb1-4c3e-bd7f-552ac33f2a11",
        "tipo": "T1",
        "codigo": "8",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-08 · INSTALACIONES HIDROSANITARIAS",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "746864d6-865e-4b6d-93c5-1c16c2e7c360",
        "tipo": "D1",
        "codigo": "8.01",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla de plomería",
        "unidad": "día",
        "cantidad": 90,
        "costo_unitario": 442,
        "margen": 15
      },
      {
        "id": "c7d1faf9-b978-4ead-b441-822c457e5de7",
        "tipo": "D3",
        "codigo": "8.02",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Tubería PVC presión y sanitaria + accesorios",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 93600,
        "margen": 15
      },
      {
        "id": "12072283-4af8-4cf8-a099-d39789cc1064",
        "tipo": "D3",
        "codigo": "8.03",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Aparatos sanitarios y grifería",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 75640,
        "margen": 15
      },
      {
        "id": "c4f10d3b-7d66-4f95-b4c2-1bab9f26a9bc",
        "tipo": "D4",
        "codigo": "8.04",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Roto-martillo perforación instalaciones",
        "unidad": "día",
        "cantidad": 40,
        "costo_unitario": 60,
        "margen": 15
      },
      {
        "id": "a7fad17d-1c7d-4809-9600-f1372440896a",
        "tipo": "T1",
        "codigo": "9",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-09 · RED DE GAS DOMICILIARIO",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "3ceace1f-faa3-4c8e-b8de-9bf293849c9e",
        "tipo": "D1",
        "codigo": "9.01",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla de instalación de red de gas",
        "unidad": "día",
        "cantidad": 35,
        "costo_unitario": 442,
        "margen": 15
      },
      {
        "id": "63d71f5b-2bb3-47f0-88d4-5ba48cade355",
        "tipo": "D3",
        "codigo": "9.02",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Tubería de gas, reguladores y accesorios",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 55200,
        "margen": 15
      },
      {
        "id": "4912459b-401c-456a-ae2a-e15f8b04dccf",
        "tipo": "D5",
        "codigo": "9.03",
        "concepto": "Subcontrato",
        "ref_id": "",
        "descripcion": "Subcontrato: Certificación y pruebas de red de gas (organismo acreditado)",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 13440,
        "margen": 15
      },
      {
        "id": "6b562ebb-531e-4b22-937d-9f488ad3d0fc",
        "tipo": "T1",
        "codigo": "10",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-10 · INSTALACIONES ELÉCTRICAS",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "4295d5eb-df18-4dde-a171-1f60cfd9a3c7",
        "tipo": "D1",
        "codigo": "10.01",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla eléctrica",
        "unidad": "día",
        "cantidad": 100,
        "costo_unitario": 455,
        "margen": 15
      },
      {
        "id": "16c84f8d-8e6f-4e4e-829b-310151012e3b",
        "tipo": "D3",
        "codigo": "10.02",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Cableado, tubería EMT y accesorios",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 114000,
        "margen": 15
      },
      {
        "id": "57ca2f97-c007-4b8f-9c8f-19cf1471c81d",
        "tipo": "D3",
        "codigo": "10.03",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Tableros, protecciones y salidas",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 58560,
        "margen": 15
      },
      {
        "id": "b35a1632-0d59-4cc8-b098-1f734e6c7697",
        "tipo": "D4",
        "codigo": "10.04",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Taladro perforador para instalaciones eléctricas",
        "unidad": "día",
        "cantidad": 45,
        "costo_unitario": 60,
        "margen": 15
      },
      {
        "id": "b3b6ebac-2a6b-42cf-b874-e58fca1d18a4",
        "tipo": "D5",
        "codigo": "10.05",
        "concepto": "Subcontrato",
        "ref_id": "",
        "descripcion": "Subcontrato: Red contra incendios y detección (llave en mano)",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 69440,
        "margen": 15
      },
      {
        "id": "85ddc43a-ae9c-49b4-818b-bcfae8534bbe",
        "tipo": "T1",
        "codigo": "11",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-11 · CORRIENTES DÉBILES: CITOFONÍA, CCTV Y DATOS",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "95439d79-f5ba-4c64-9c48-ae40251b9242",
        "tipo": "D2",
        "codigo": "11.01",
        "concepto": "MOI",
        "ref_id": "",
        "descripcion": "Coordinación técnica de instalaciones especiales",
        "unidad": "mes",
        "cantidad": 4,
        "costo_unitario": 6240,
        "margen": 15
      },
      {
        "id": "8893c385-560d-4187-b10b-434ea84f2590",
        "tipo": "D5",
        "codigo": "11.02",
        "concepto": "Subcontrato",
        "ref_id": "",
        "descripcion": "Subcontrato: Citofonía y control de acceso (llave en mano)",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 64960,
        "margen": 15
      },
      {
        "id": "b2697476-e3c6-47d3-bceb-aed344419e06",
        "tipo": "D5",
        "codigo": "11.03",
        "concepto": "Subcontrato",
        "ref_id": "",
        "descripcion": "Subcontrato: CCTV y cableado estructurado (llave en mano)",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 80640,
        "margen": 15
      },
      {
        "id": "5e5969b5-a225-4e3e-8f7c-2da14c130971",
        "tipo": "T1",
        "codigo": "12",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-12 · VENTILACIÓN MECÁNICA Y EXTRACCIÓN",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "a762e267-1b76-469a-9b7e-d498b4237956",
        "tipo": "D3",
        "codigo": "12.01",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Ductos, rejillas y accesorios",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 28800,
        "margen": 15
      },
      {
        "id": "ff4469dd-9236-43a9-ab7d-a287390e749f",
        "tipo": "D5",
        "codigo": "12.02",
        "concepto": "Subcontrato",
        "ref_id": "",
        "descripcion": "Subcontrato: Ventilación de sótanos y extracción de baños (llave en mano)",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 107520,
        "margen": 15
      },
      {
        "id": "bac8a2db-d73b-43ec-a60f-b2389deeb9df",
        "tipo": "T1",
        "codigo": "13",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-13 · EQUIPOS HIDRÁULICOS: BOMBEO, TANQUES Y PRESIÓN",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "40a0531a-f2ed-4f73-8ba7-dce82578b9b3",
        "tipo": "D1",
        "codigo": "13.01",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla de montaje hidráulico",
        "unidad": "día",
        "cantidad": 25,
        "costo_unitario": 442,
        "margen": 15
      },
      {
        "id": "ca47ba44-8337-4cfb-89db-a39d52929ab0",
        "tipo": "D3",
        "codigo": "13.02",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Tanques de almacenamiento de agua potable",
        "unidad": "un",
        "cantidad": 2,
        "costo_unitario": 21600,
        "margen": 15
      },
      {
        "id": "b3130332-b431-4cda-a70b-38c057899753",
        "tipo": "D5",
        "codigo": "13.03",
        "concepto": "Subcontrato",
        "ref_id": "",
        "descripcion": "Subcontrato: Equipo de presión constante y bombeo (suministro e instalación)",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 98560,
        "margen": 15
      },
      {
        "id": "08149c6a-2233-413e-b469-0d3b539fd4df",
        "tipo": "T1",
        "codigo": "14",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-14 · ACABADOS (PISOS, ENCHAPES Y PINTURA)",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "7f1ff4d0-5e3d-476d-97ca-7b8398f8aeaf",
        "tipo": "D1",
        "codigo": "14.01",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla de enchapes y pisos",
        "unidad": "día",
        "cantidad": 140,
        "costo_unitario": 429,
        "margen": 15
      },
      {
        "id": "c65c33bd-6327-476c-809f-92a54a07e358",
        "tipo": "D1",
        "codigo": "14.02",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla de estuco y pintura",
        "unidad": "día",
        "cantidad": 120,
        "costo_unitario": 416,
        "margen": 15
      },
      {
        "id": "9097f23a-aa82-4361-a965-93e5363f9f20",
        "tipo": "D3",
        "codigo": "14.03",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Cerámica / porcelanato",
        "unidad": "m²",
        "cantidad": 3200,
        "costo_unitario": 82.96,
        "margen": 15
      },
      {
        "id": "cd685724-587a-4bf4-a3e4-3a2bd56823a0",
        "tipo": "D3",
        "codigo": "14.04",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Estuco, pintura y vinilos",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 51240,
        "margen": 15
      },
      {
        "id": "e495f910-3160-4d2a-8b3b-61d1819fe7c8",
        "tipo": "D3",
        "codigo": "14.05",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Enchape de baños y cocinas",
        "unidad": "m²",
        "cantidad": 1400,
        "costo_unitario": 67.1,
        "margen": 15
      },
      {
        "id": "47d76eba-ccb6-4688-93c0-cc0fe199951d",
        "tipo": "D5",
        "codigo": "14.06",
        "concepto": "Subcontrato",
        "ref_id": "",
        "descripcion": "Subcontrato: Suministro e instalación de ascensores",
        "unidad": "un",
        "cantidad": 2,
        "costo_unitario": 201600,
        "margen": 15
      },
      {
        "id": "23724c23-6fb2-4e83-9d19-a70faa2e91f1",
        "tipo": "T1",
        "codigo": "15",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-15 · CARPINTERÍA, VENTANERÍA Y CUBIERTA",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "02280304-aaf0-4f86-921a-ec964b7d3c5e",
        "tipo": "D1",
        "codigo": "15.01",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla de instalación carpintería / ventanería",
        "unidad": "día",
        "cantidad": 80,
        "costo_unitario": 442,
        "margen": 15
      },
      {
        "id": "a9840d20-ed45-4c35-921a-2daf1a396d46",
        "tipo": "D3",
        "codigo": "15.02",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Puertas y carpintería en madera",
        "unidad": "un",
        "cantidad": 220,
        "costo_unitario": 585.6,
        "margen": 15
      },
      {
        "id": "1f451ab6-d5b4-4dd5-9a7d-b6bbced3ad56",
        "tipo": "D3",
        "codigo": "15.03",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Ventanería en aluminio + vidrio",
        "unidad": "m²",
        "cantidad": 780,
        "costo_unitario": 237.9,
        "margen": 15
      },
      {
        "id": "3ae165a3-bb02-4bdd-a651-71245158c958",
        "tipo": "D3",
        "codigo": "15.04",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Impermeabilización y cubierta",
        "unidad": "m²",
        "cantidad": 620,
        "costo_unitario": 102,
        "margen": 15
      },
      {
        "id": "5c01a607-2fc1-4c74-8055-fef009c12cc7",
        "tipo": "D4",
        "codigo": "15.05",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Taladro / atornillador y pulidora (carpintería)",
        "unidad": "día",
        "cantidad": 35,
        "costo_unitario": 66,
        "margen": 15
      },
      {
        "id": "40b554a9-c200-46d9-8350-57dab0485f7a",
        "tipo": "D5",
        "codigo": "15.06",
        "concepto": "Subcontrato",
        "ref_id": "",
        "descripcion": "Subcontrato: Muro cortina / fachada flotante (llave en mano)",
        "unidad": "m²",
        "cantidad": 320,
        "costo_unitario": 483,
        "margen": 15
      },
      {
        "id": "dfb77e08-5575-46df-a108-f0898de8b3a8",
        "tipo": "T1",
        "codigo": "16",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-16 · MUEBLES FIJOS: COCINAS INTEGRALES Y CLOSETS",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "6f00f5f3-7c51-4bde-a44e-bb769ce2dae4",
        "tipo": "D5",
        "codigo": "16.01",
        "concepto": "Subcontrato",
        "ref_id": "",
        "descripcion": "Subcontrato: Cocinas integrales (suministro e instalación)",
        "unidad": "un",
        "cantidad": 40,
        "costo_unitario": 7820,
        "margen": 15
      },
      {
        "id": "f3b8cacb-7458-4107-b1da-4a9e435eb871",
        "tipo": "D5",
        "codigo": "16.02",
        "concepto": "Subcontrato",
        "ref_id": "",
        "descripcion": "Subcontrato: Closets y muebles de baño (suministro e instalación)",
        "unidad": "un",
        "cantidad": 40,
        "costo_unitario": 4830,
        "margen": 15
      },
      {
        "id": "4a16425e-9b6e-445b-a6c2-4c4e5f5b53d8",
        "tipo": "T1",
        "codigo": "17",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-17 · URBANISMO, EXTERIORES Y PAISAJISMO",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "7e38b223-cfa3-4e5b-b640-463a5df4f676",
        "tipo": "D1",
        "codigo": "17.01",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla de andenes, sardineles y exteriores",
        "unidad": "día",
        "cantidad": 70,
        "costo_unitario": 429,
        "margen": 15
      },
      {
        "id": "9f4e9248-2527-4961-ac4a-5ad2e47627ac",
        "tipo": "D3",
        "codigo": "17.02",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Concreto para andenes y sardineles",
        "unidad": "m³",
        "cantidad": 90,
        "costo_unitario": 624,
        "margen": 15
      },
      {
        "id": "e6ab7a93-e3be-4f17-9600-f3fe7c8ad7d1",
        "tipo": "D3",
        "codigo": "17.03",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Adoquín, grama y jardinería",
        "unidad": "m²",
        "cantidad": 850,
        "costo_unitario": 75.64,
        "margen": 15
      },
      {
        "id": "de64674d-3e3f-4057-a2d4-0ca671c7af45",
        "tipo": "D4",
        "codigo": "17.04",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Minicargador / compactador para exteriores",
        "unidad": "día",
        "cantidad": 25,
        "costo_unitario": 216,
        "margen": 15
      },
      {
        "id": "75801916-adff-40fe-85b6-3f8f204bec40",
        "tipo": "D5",
        "codigo": "17.05",
        "concepto": "Subcontrato",
        "ref_id": "",
        "descripcion": "Subcontrato: Portería, cerramiento definitivo y obras exteriores",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 89700,
        "margen": 15
      },
      {
        "id": "156fe93a-24af-4b9d-b9ee-fb16ad32ca08",
        "tipo": "T1",
        "codigo": "18",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-18 · SEGURIDAD INDUSTRIAL (SST), ANDAMIOS Y EQUIPOS DE ALTURA",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "2334834f-1277-40b1-9d85-d6da1dbca3b2",
        "tipo": "D2",
        "codigo": "18.01",
        "concepto": "MOI",
        "ref_id": "",
        "descripcion": "Coordinador SST / seguridad industrial",
        "unidad": "mes",
        "cantidad": 10,
        "costo_unitario": 5850,
        "margen": 15
      },
      {
        "id": "b8cb9c8e-5eae-474f-b612-d97bc12fb51f",
        "tipo": "D3",
        "codigo": "18.02",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Dotación, EPP y señalización de obra",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 38400,
        "margen": 15
      },
      {
        "id": "06bdd1b2-990a-4bdd-85a6-d7ef4aebde00",
        "tipo": "D4",
        "codigo": "18.03",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Alquiler andamio certificado multidireccional (torre-mes)",
        "unidad": "un",
        "cantidad": 60,
        "costo_unitario": 744,
        "margen": 15
      },
      {
        "id": "d867f919-f592-4ed0-a19c-b7cb6aeb7f01",
        "tipo": "D4",
        "codigo": "18.04",
        "concepto": "Maquinaria y Vehículos",
        "ref_id": "",
        "descripcion": "Alquiler malacate / montacargas de obra",
        "unidad": "mes",
        "cantidad": 8,
        "costo_unitario": 6136,
        "margen": 15
      },
      {
        "id": "bb7317ed-c767-472d-85ae-4ab26603fc80",
        "tipo": "T1",
        "codigo": "19",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-19 · ASEO GENERAL, RESANE Y ENTREGA",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "f747a3c5-415a-4280-b86b-1925df74b1c9",
        "tipo": "D1",
        "codigo": "19.01",
        "concepto": "MOD",
        "ref_id": "",
        "descripcion": "Cuadrilla de aseo general y resane final",
        "unidad": "día",
        "cantidad": 60,
        "costo_unitario": 390,
        "margen": 15
      },
      {
        "id": "6c27dc75-5b11-4e9a-bde5-e0285f830dc0",
        "tipo": "D3",
        "codigo": "19.02",
        "concepto": "Materiales",
        "ref_id": "",
        "descripcion": "Insumos de aseo, resane y protección",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 16800,
        "margen": 15
      },
      {
        "id": "60981360-43c4-4102-b0b8-a660c67d41c8",
        "tipo": "D6",
        "codigo": "19.03",
        "concepto": "Otro",
        "ref_id": "",
        "descripcion": "Retiro de escombros y disposición final",
        "unidad": "vje",
        "cantidad": 60,
        "costo_unitario": 224.2,
        "margen": 15
      },
      {
        "id": "8df3ffa4-f7f6-4bbe-a5f0-61fa3d0b73aa",
        "tipo": "T1",
        "codigo": "20",
        "concepto": "",
        "ref_id": "",
        "descripcion": "E-20 · MOVILIZACIÓN, TRANSPORTE Y VIAJES",
        "unidad": "",
        "cantidad": 0,
        "costo_unitario": 0,
        "margen": 0
      },
      {
        "id": "b6b4a46e-8d43-478c-b96b-5aab5b6f0535",
        "tipo": "D6",
        "codigo": "20.01",
        "concepto": "Otro",
        "ref_id": "",
        "descripcion": "Transporte de materiales a obra (fletes)",
        "unidad": "vje",
        "cantidad": 140,
        "costo_unitario": 259.6,
        "margen": 15
      },
      {
        "id": "bccca277-4c81-4c26-b8d7-208159dee663",
        "tipo": "D6",
        "codigo": "20.02",
        "concepto": "Otro",
        "ref_id": "",
        "descripcion": "Movilización de equipos y grúa torre",
        "unidad": "gl",
        "cantidad": 1,
        "costo_unitario": 80240,
        "margen": 15
      },
      {
        "id": "f1176c95-6985-40a9-8901-037ae0969860",
        "tipo": "D6",
        "codigo": "20.03",
        "concepto": "Otro",
        "ref_id": "",
        "descripcion": "Viáticos y alojamiento personal foráneo",
        "unidad": "día",
        "cantidad": 1200,
        "costo_unitario": 74.75,
        "margen": 15
      },
      {
        "id": "8976c56d-b9e0-4cc1-888b-beebed4ceac6",
        "tipo": "D6",
        "codigo": "20.04",
        "concepto": "Otro",
        "ref_id": "",
        "descripcion": "Transporte y viajes del personal",
        "unidad": "mes",
        "cantidad": 10,
        "costo_unitario": 4830,
        "margen": 15
      }
    ],
    "situacion": "Borrador",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-07-12T09:00:00.000Z",
    "monto_calculado": 7691614.919999999,
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "responsable_tecnico": "Juan Andres Arango",
    "unidad_negocio": "Construcción",
    "lugar_ejecucion": "Lima",
    "codigo_gtm": "GTM-OF-00002",
    "comercial": "Karina Cardona"
  }
]
