// Traducción al inglés del contenido del Manual, por id de tarjeta.
// Se usa cuando el idioma seleccionado es 'en'. Si una tarjeta o campo no
// está aquí, se cae al contenido en español (ver useLoc en page.tsx).

export type TarjetaEN = {
  titulo?: string
  intro?: string
  puntos?: string[]
  pasos?: string[]
  campos?: { n: string; d: string }[]
  notas?: string[]
}

export const MANUAL_EN: Record<string, TarjetaEN> = {
  'introduccion': {
    titulo: 'Introduction',
    intro: 'In every company, one of the areas with the greatest responsibility for making the business sustainable over time is the Commercial Area. Nearly 100% of its actions target three key moments of the process, and a CRM gives you the complete and controlled view of the tracking and management of customer relationships.',
    puntos: [
      '1) ATTRACT — Marketing: capturing new customers with strategies that combine the digital with the traditional.',
      '2) SELL — Sales: showcasing what is offered and the company\'s experience, quoting jobs or issuing offers defined by the customer, and thus closing deals. Those closed sales are the revenue that allows the company to continue its life in the business world.',
      '3) SERVE — Customer Service: the hardest part is not selling and meeting a quota, but keeping the customer very well served, handling every request or incident professionally and as quickly as possible.',
    ],
    notas: [
      'Strategic decision — Two CRMs, two businesses: After a detailed analysis together with Eng. José E. Palomares, the decision was made to operate with TWO independent systems: this CRM for the NORTON COMMERCIAL BUSINESSES, and a second CRM for the GRUPO GTM / TAMOIN businesses (construction works, offers and bids). Benefits in every aspect: (1) data 100% isolated and confidential — the information of one business is never mixed with that of the other; (2) each system with its own database, backups and access, so an incident in one does not affect the other; (3) each CRM with its own identity, modules and focus (Norton = commercial; GTM = construction/APU); (4) both multi-country and bilingual (ES/EN), scalable and maintained separately with no cross-risk; (5) full operational clarity: each team works in its own system, without noise from the other.',
      'The result of serving well: favorable comments and recommendations that position the company as a benchmark in the business world.',
      'That is why the CRM: it brings together Marketing + Sales + Customer Service in a single place, with the complete and controlled view of the relationship with each customer.',
      'MULTI-COUNTRY Tip — This CRM (GESTIÓN COMERCIAL NORTON) handles several countries. Each user is assigned their Country and sees ONLY the information of their country; GLOBAL users (Admin / HQ) see all countries. Currencies by country: Colombia → Pesos (COP $) · Peru → Soles (S/) · Ecuador → Dollar (US$). The location adapts to the structure of each country (Colombia: Region → Department → City · Peru: Department → Province → District). The Products module also filters by country: each product belongs to a country and the user sees only those of their country (GLOBAL sees all, with the 🌎 filter).',
      'BILINGUAL Tip — The system is bilingual Spanish / English. With the little flag in the header (🇪🇸 / 🇺🇸) you switch the language and the module titles and field names are translated instantly.',
    ],
  },
  'clientes': {
    titulo: 'Customers',
    intro: 'This is where the companies that are Customers of the Company are recorded. The key field is the Customer Type.',
    puntos: [
      'Customer Type: companies that are ALREADY customers are identified as "Customer".',
      'When a company is still just a prospect (the Opportunity has not yet been created) and its status indicates that it "Requires an Offer or Quote", the "Convert to Customer" button is pressed from the Prospects module.',
      'Upon conversion, the system automatically assigns it the "Prospect" Type.',
      'That way, when creating the Opportunity, when the Customer is requested, the report shows the Name and the Type it has at that moment (Customer or Prospect), and from there you continue with the Opportunity data.',
    ],
    campos: [
      { n: 'Code', d: 'Automatic sequential number (CLI-XXXXX).' },
      { n: 'ID Type / Document No.', d: 'RUC, DNI, etc. and its number.' },
      { n: 'Customer Type', d: 'Customer or Prospect.' },
      { n: 'Legal Name / Trade Name', d: 'Legal and commercial name.' },
      { n: 'Activity', d: 'Economic activity (from References).' },
      { n: 'Phone / Email / Website', d: 'Contact details.' },
      { n: 'Location', d: 'Address, Country, Region, Department, City and Postal Code.' },
      { n: 'Payment Terms / Currency', d: 'Commercial terms (Pesos by default).' },
      { n: 'Status', d: 'Active, Inactive, Prospect.' },
      { n: 'PQR Access Code', d: 'Generated automatically (see note).' },
    ],
    notas: [
      'Location — Colombia methodology: the location works by CASCADE with the country structure: Region → Department → City. Each level filters the next.',
      'Automatic PQR Code: when creating a Customer-type Company, the system generates a PQR Access Code so that in the future it can register Incidents, Complaints, Suggestions, etc. through the public PQRS form.',
      'Follow-up Log: when entering to View a company, all the management is recorded (Date, Time, Detail, Person and Status). IMPORTANT: the Status placed at the end of the follow-up line automatically updates the Status of the module\'s main record.',
      'Attach files: in each record you can upload photos, images and documents (PDF, Word, Excel), up to 50 MB per file, to keep the supporting documents and evidence in a single place.',
    ],
  },
  'contactos': {
    titulo: 'Contacts',
    intro: 'This module stores the data of the people who work at the customer companies, in order to have the necessary contact information at hand.',
    puntos: [
      'It is VERY important to keep them updated: people change positions or leave the company, and outdated data causes lost time and opportunities.',
      'Each contact is associated with a Company (customer) registered in the Customers module.',
      'A contact can be marked as Primary to quickly identify the key point of contact for that company.',
    ],
    campos: [
      { n: 'Code', d: 'Automatic sequential number (CON-XXXXX).' },
      { n: 'Company', d: 'Company/customer the person belongs to (from Customers).' },
      { n: 'First Name / Last Name', d: 'The person\'s data.' },
      { n: 'Job Title', d: 'Position held at the company.' },
      { n: 'Department / Area', d: 'Area they belong to within the company.' },
      { n: 'Phone / Mobile', d: 'Contact numbers.' },
      { n: 'Email', d: 'Contact email.' },
      { n: 'Date of Birth', d: 'Useful for greetings and loyalty building.' },
      { n: 'Level of Influence', d: 'Decision-maker, Influencer, etc. (from References).' },
      { n: 'Primary Contact', d: 'Marks whether they are the company\'s main point of contact.' },
      { n: 'Notes', d: 'Additional notes.' },
      { n: 'Status', d: 'Active / Inactive.' },
    ],
    notas: [
      'Keep them up to date: when a contact changes position or leaves the company, update their record or change it to "Inactive" Status to preserve the history without losing information.',
      'Each contact has its own Follow-up Log to record the actions taken with that person. The Status placed on the follow-up line automatically updates the contact\'s Status.',
      'Attach files: in each record you can upload photos, images and documents (PDF, Word, Excel), up to 50 MB per file.',
    ],
  },
  'prospectos': {
    titulo: 'Prospects',
    intro: 'The goal of the Prospects module is to manage potential customers (leads): people or companies that are interested but are NOT yet formal customers. Here they are captured, qualified and followed up before converting them into a Customer and creating an Opportunity, so that no interested party is lost due to lack of management.',
    puntos: [
      'Why a Prospects module? To separate interested parties (leads) from real customers: they are first captured and qualified here, without cluttering the Customers database.',
      'A prospect can be registered manually within the CRM or arrive through Norton\'s Public Form / Landing page.',
      'Commercial follow-up is done (calls, emails) until they are qualified or discarded.',
      'When their status indicates that they "Require an Offer/Quote", "Convert to Customer" is pressed (it remains with Prospect Type) and from there the Opportunity is created.',
    ],
    pasos: [
      '1) The interested party fills out Norton\'s Public Form / Landing page (name, company, email, requirement).',
      '2) That lead does NOT go directly into the CRM: it first lands in an INBOX (pending import).',
      '3) The Prospects screen refreshes itself every ~15 seconds and ALERTS with a red badge showing how many prospects are pending to be added.',
      '4) The user opens the inbox and reviews each lead (thus filtering spam or incomplete data before they enter the database).',
      '5) Press "Import to CRM" (or "Import All") to move them into the Prospects list. They enter with Origin = "Web Form".',
      '6) The system sends the prospect an automatic confirmation email.',
      '7) They are followed up in the log until qualified; when they "Require an Offer/Quote", "Convert to Customer" is pressed and the Opportunity is created.',
    ],
    campos: [
      { n: 'Code', d: 'Automatic sequential number (PRS-XXXXX).' },
      { n: 'Registration Date', d: 'Current date (automatic).' },
      { n: 'First Name / Last Name', d: 'The person\'s data (stored in UPPERCASE).' },
      { n: 'Company', d: 'Company the prospect belongs to.' },
      { n: 'Email / Mobile No.', d: 'Contact details.' },
      { n: 'Prospect Origin', d: 'How they arrived: Web, Referral, Call, etc. (from References).' },
      { n: 'Referred By / Referring Company', d: 'Who and which company referred them.' },
      { n: 'Activity', d: 'Economic activity (from References).' },
      { n: 'Location', d: 'Cascade Country → Region → Department → City, same as in Customers.' },
      { n: 'Requirement Detail', d: 'What the prospect needs or requests.' },
      { n: 'Status', d: 'New, Not Contacted, Contacted, Qualified, Requires Offer/Quote, Converted, Discarded, etc. (from References).' },
    ],
    notas: [
      'Follow-up Log: each prospect has its log (Date, Time, Detail, Person and Status). The Status placed on the follow-up line automatically updates the prospect\'s Status.',
      'Capture from the Norton Landing page: prospects arriving through the public form are NOT saved directly. They first land in an INBOX; the screen refreshes itself every 15 seconds and ALERTS with a red badge showing the number of pending items. The user must press "Import to CRM" (or "Import All") to move them into the record.',
      'Why is it NOT added automatically? So that a person reviews and validates each lead before it enters the database: this filters out spam/junk and keeps the CRM from being contaminated with unwanted automatic records. Upon import they enter with Origin = "Web Form", and the system sends the prospect an automatic confirmation email.',
      'Attach files: in each record you can upload photos, images and documents (PDF, Word, Excel), up to 50 MB per file.',
    ],
  },
  'oportunidades': {
    titulo: 'Opportunities',
    intro: 'An Opportunity is a concrete deal in progress: a real sales possibility with an identified customer who has already moved from mere interest to a purchase intention. This module is the SALES PIPELINE: it lets you forecast, follow up and close each deal knowing how much it is worth, what stage it is in and what probability it has of being won.',
    puntos: [
      'Where it comes from: usually from a Prospect converted to Customer. When creating the Opportunity, the Customer is requested and the system brings its Name and Type (Customer or Prospect) at that moment; from there you continue with the deal data.',
      'Each Opportunity is associated with a Customer and a Contact, and optionally with a Project.',
      'It handles two amounts in parallel: Estimated COP (pesos $) and Estimated USA (dollars US$).',
      'The Probability (%) and the Stage let you see the funnel and prioritize the deals closest to closing.',
      'The entire cycle is tracked: inquiry dates, offer presentation, expected verdict and closing (Won / Lost).',
    ],
    campos: [
      { n: 'Code', d: 'Automatic sequential number (OPP-XXXXX).' },
      { n: 'Project / Customer / Contact', d: 'Which project and with whom the opportunity is associated.' },
      { n: 'Estimated COP / Estimated USA', d: 'Estimated deal amount in pesos ($) and in dollars (US$).' },
      { n: 'Stage', d: 'Pipeline stage (Prospecting, Qualification, Proposal, Negotiation, Closing… from References). Feeds the Pipeline chart on the Dashboard.' },
      { n: 'Status', d: 'Open, In Negotiation, Won, Lost.' },
      { n: 'Probable % / Year Execution % / MGC', d: 'Indicators of closing probability, year-to-date progress and margin (MGC).' },
      { n: 'Owner', d: 'Assigned salesperson (from References → Salespeople).' },
      { n: 'Process dates', d: 'Start/end of inquiries, offer presentation and expected verdict.' },
      { n: 'Award / Verdict / Winning Company', d: 'Tracking of the closing outcome.' },
      { n: 'Actual Offer Amount', d: 'Value with which the offer was finally submitted.' },
      { n: 'Notes', d: 'Additional notes and details of the deal.' },
    ],
    notas: [
      'Required Documents: within the opportunity, the documents requested by the bid/offer are listed, so none is left pending.',
      'Pipeline on the Dashboard: the amounts by Stage feed the "Sales Pipeline" chart on the dashboard, to see the complete funnel at a glance.',
      'Follow-up Log: records all the management (Date, Time, Detail, Person and Status). The follow-up Status automatically updates the opportunity\'s Status.',
      'Attach files: in each record you can upload photos, images and documents (PDF, Word, Excel), up to 50 MB per file.',
    ],
  },
  'control-proyectos': {
    titulo: 'Project Control',
    intro: 'Project Control is the CONSTRUCTION MANAGEMENT DASHBOARD: it tracks each project in execution showing physical progress, financial progress, billing, costs and schedule compliance, with the S-CURVE as the central tool to compare planned versus executed. It replaces the control currently kept in Excel and gives Management an immediate view to decide. It is a module independent from the Projects module; it is distinguished in orange while it is 🚧 UNDER CONSTRUCTION.',
    puntos: [
      'Project sheet with its budget/baseline, which can be taken from the won Offer to avoid double data entry.',
      'Hierarchical WBS (Chapter > Item > Sub-item) with the weight of each item; it can be IMPORTED from the construction control Excel.',
      'Progress cutoffs by period (weekly/monthly): % planned vs % actual. Each cutoff remains an immutable historical record.',
      'Physical (%) and financial ($) S-Curves that draw themselves with each cutoff.',
      'Management Summary (KPIs): budget, progress, budgeted and projected margin, actual margin to date, billing and pending balance to bill.',
      'Portfolio with traffic-light indicator (green/amber/red) according to each project\'s progress deviation.',
      'Receivables by aging, automatic threshold alerts and export of the one-page executive summary.',
    ],
    campos: [
      { n: 'Control No.', d: 'Automatic sequential number (CTP-XXXX).' },
      { n: 'Project / Customer', d: 'Name of the construction work and associated customer.' },
      { n: 'Link Offer', d: 'Brings customer, project, currency and budget from the won offer.' },
      { n: 'Budget / Baseline', d: 'Total approved value; basis of all calculations.' },
      { n: 'Items (WBS)', d: 'Breakdown by chapters/items with unit, quantity, unit price, total and weight %.' },
      { n: 'Progress Cutoffs', d: '% plan and % actual accumulated per period (feed the S-Curve).' },
      { n: 'Financial data', d: 'Costs, projected value, income, expenses and billing (feed the KPIs).' },
      { n: 'Receivables', d: 'Accounts receivable by aging (0–30, 31–60, 60+ days).' },
    ],
    pasos: [
      '1) Press "+ New Control" and fill in the base data — or link the won Offer to auto-fill.',
      '2) In Items (WBS) import the construction Excel (or capture the items manually).',
      '3) Record the Progress Cutoffs (% plan and % actual) — the S-Curve draws itself.',
      '4) Complete the Financial data and Receivables → the KPIs and alerts are calculated.',
      '5) Review the Portfolio with traffic-light indicators and export the executive summary for the construction committee.',
    ],
    notas: [
      'The S-Curve is the central tool: when the actual line runs below the planned one, the project is behind; the distance is the accumulated deviation.',
      'Traffic light: 🟢 green (on time), 🟠 attention (deviation −5% to −10%), 🔴 critical (−10% or worse).',
      'Its own manual: the system has its own "Procedures and Usage Manual" as the first option, with more detail and a downloadable PDF.',
      'Independent and reversible module: it does not touch the current Projects module; it is marked in orange while UNDER CONSTRUCTION.',
    ],
  },
  'cotizaciones': {
    titulo: 'Quotes',
    intro: 'Quotes are the commercial heart of the CRM: it is where all the scattered information comes together to produce a formal proposal in minutes. It optimizes and speeds up the work because it REUSES the data that already lives in the system —the customer, its contacts, the products and their prices— avoiding re-entry and reducing errors. Instead of building each offer by hand, it is generated consistently, with its automatic calculations and taxes.',
    puntos: [
      'It connects with the Customers master: you choose the Company and it brings its name and its contact; it can also be linked to an Opportunity to provide traceability to the deal.',
      'It connects with the Products master: the Quote Type (Category) filters which products can be added as line items, with their price already loaded.',
      'It speeds everything up: the totals, taxes and (in construction) the AIU are calculated automatically — zero manual math.',
      'Each proposal carries its Status (Draft, Sent, Approved, Rejected, Expired) to track the state of the deal.',
    ],
    campos: [
      { n: 'Code / No.', d: 'Quote identification (automatic).' },
      { n: 'Issue Date / Expiration', d: 'Date of the proposal and until when it is valid.' },
      { n: 'Company / Contact', d: 'Who the quote is for (from the Customers master).' },
      { n: 'Opportunity', d: 'Deal the quote is associated with (optional, for traceability).' },
      { n: 'Quote Type', d: 'REQUIRED. Chosen at the start (Products Category) and defines which products can be added in the line items.' },
      { n: 'Currency / Payment Terms / Tax % / Salesperson', d: 'Commercial conditions of the offer.' },
      { n: 'Items (line items)', d: 'Products, quantity, price, discount and subtotal.' },
      { n: 'AIU (Construction only)', d: 'Administration, Contingencies and Profit; activated when the type is Construction.' },
      { n: 'Status', d: 'Draft, Sent, Approved, Rejected, Expired.' },
    ],
    notas: [
      'Generate PDF and send by email: with one click the quote PDF is generated and can be sent directly to the Customer and/or Prospect by email. The PDF and the email reflect the same breakdown (including AIU if it is Construction).',
      'Calculation according to the Type: in Services the Tax is applied on the Subtotal; in Construction the AIU is activated (Administration, Contingencies, Profit) and the tax is settled on the Profit.',
      'Follow-up Log: records the management of each quote; the follow-up Status updates the quote\'s Status.',
      'Attach files: in each record you can upload photos, images and documents (PDF, Word, Excel), up to 50 MB per file.',
    ],
  },
  'ofertas': {
    titulo: 'Offers',
    intro: 'The Offers subsystem is the engine for preparing CONSTRUCTION / BID BUDGETS at the APU (Unit Price Analysis) level. Unlike a simple quote, here a detailed offer is built by CHAPTERS and LINE ITEMS, pulling the real costs from the masters (Personnel, Miscellaneous Products, Machinery and Contractors), and calculating profit margin, taxes and the total amount — all ready to present professional reports to the customer.',
    puntos: [
      '📋 OFFERS BUDGET — What it does: it is the offer/bid itself (code PR-XXXXX), the central document of the subsystem. How it works: a header is filled in (Customer, Project, Country, Currency, Profit % and Tax %) and the budget is built with line items organized by Chapters (Titles) and Details (D1=MOD, D2=MOI, D3=Materials, D4=Machinery, D5=Subcontract, D6=Other). Each Detail pulls its cost from the corresponding master and the system calculates unit price, sale, profit and tax automatically. From here the Official, APU and Chart reports are generated.',
      '🗂️ OFFER CHAPTERS — What it does: defines the standard structure of the budget (e.g. E-01 Studies, E-02 Preliminaries, E-03 Earthworks…). How it works: they are created once as a master of titles/subchapters and reused in each offer; they group the line items and allow subtotals by chapter to be seen, giving order and quick reading to the budget.',
      '👷 CONTRACTORS — What it does: it is the master of subcontractor companies/individuals (data, specialty, contact). How it works: register each contractor once; it serves as the basis for Subcontract-type line items and for associating budgets with them.',
      '📑 CONTRACTORS BUDGET — What it does: stores the budgets that each contractor delivers for a construction work or offer. How it works: the subcontract items and costs are recorded; those values feed the Subcontract-type line items (D5) of the offer with real, not estimated, costs.',
      '🧱 MISCELLANEOUS PRODUCTS — What it does: master of materials and supplies with their unit and cost. How it works: each material keeps its price; when adding a Materials-type line item (D3) in the offer, it pulls the cost from here. Keeping it up to date ensures real prices.',
      '🚜 MACHINERY AND EQUIPMENT — What it does: master of machinery and equipment with their cost (per hour/day). How it works: it feeds the Machinery and Vehicles-type line items (D4); when choosing the equipment in the offer, it brings its cost automatically.',
      '💼 POSITIONS AND SALARIES — What it does: master of personnel with position, salary and loaded daily cost (includes benefits). How it works: it feeds the MOD (direct labor, D1) and MOI (indirect, D2) line items; the personnel cost in the offer comes from here.',
      '🏗️ CONSTRUCTION TRACKING — What it does: controls the execution of the construction work once the offer has been awarded. How it works: it records progress, dates and statuses of each construction work/project, to monitor how the execution is going against what was budgeted.',
    ],
    pasos: [
      '1) Prepare the masters: register your Positions and Salaries, Miscellaneous Products, Machinery and Equipment and Contractors — the costs of each line item will come from there.',
      '2) Create the Offer Chapters (Titles and subchapters) that will structure the budget.',
      '3) In Offers Budget press "+ New Offer" and fill in the header: Customer, Project, Country, Currency, general Profit %, Tax % and Scope.',
      '4) Add the line items: each one is a Title (chapter) or a Detail (D1=MOD, D2=MOI, D3=Materials, D4=Machinery, D5=Subcontract, D6=Other). When choosing the concept, the line item pulls the resource from its master with its cost.',
      '5) Adjust the quantities and the margin % (general or by chapter). The system calculates unit price, sale and tax automatically.',
      '6) Save. In the list, with the "View" button you open the complete budget with its subtotals by chapter and the grand total.',
      '7) Generate the reports: 📄 Official (formal offer for the customer), 🖨 APU (detailed unit price analysis) and 📊 Chart (visual summary by concept). They are saved as PDF or printed.',
    ],
    notas: [
      'APU engine: each Detail line item pulls its cost from the corresponding master (Positions / Miscellaneous Products / Machinery / Contractors). That is why it is KEY to keep the masters up to date.',
      'Multi-country: each offer carries its Country. GLOBAL users see all the offers; a user from a country sees only those of their country. The 🌎 filter lets you view by country (Colombia, Peru, Ecuador).',
      'Color-coded concepts: MOD, MOI, Materials, Machinery and Vehicles, Subcontract and Other are distinguished by color for quick reading of the budget.',
      'Transparency: the reports show the complete breakdown (Costs, Sales and Profit), to present the offer with total clarity to the customer.',
    ],
  },
  'pqrs': {
    titulo: 'PQRS',
    intro: 'Customer service is what builds loyalty —or loses— a company. This module centralizes PQRS (Requests, Complaints, Claims and Suggestions) to provide an optimized, fast and efficient customer service: each case is recorded, prioritized and followed up until its closure, so that nothing is lost or forgotten and the customer feels supported.',
    puntos: [
      'Reception from the WEB: if the Web Claims system is used, the customer files their PQRS from the public form, without calling or writing emails.',
      'IMPORTANT: only a customer ALREADY VALIDATED by the Company can file through the web. They must use the PQR Access Code that the system automatically assigns when registering them as a Customer (Customers module).',
      'As in Prospects, web PQRS do NOT go directly in: they land in an inbox, the system alerts and the user Imports them to the CRM. This prevents spam and filings by unauthorized third parties.',
    ],
    campos: [
      { n: 'Code / Date', d: 'Case identification and registration date.' },
      { n: 'Incident Type', d: 'Request, Complaint, Claim or Suggestion (from References).' },
      { n: 'Priority', d: 'Urgency of the case (from References).' },
      { n: 'Company / Customer', d: 'Who reports; identified by their PQR Access Code.' },
      { n: 'Subject', d: 'Summary of the case.' },
      { n: 'Notice Date / Notice Time', d: 'When the customer notified.' },
      { n: 'Reporting Person / Mobile', d: 'Who reports and their contact number.' },
      { n: 'Case Person / Mobile', d: 'Person responsible for handling the case and their contact.' },
      { n: 'Incident Detail', d: 'Description of what happened.' },
      { n: 'Status / Closing Date', d: 'Open, In Progress, Closed; and when it was resolved.' },
    ],
    notas: [
      'PQR Access Code: generated only when creating a Customer-type Company. It is the key that guarantees that only real and validated customers can file through the web; without that code, a third party cannot report.',
      'TIP — In sync with Commercial CRM: the Web Claims system must work connected to the Commercial CRM. The public form validates the Access Code against the Commercial CRM Customers, shows the Company data (Norton Colombia) and delivers the PQRS to the CRM inbox for import. This way the web channel and the CRM work as a single system.',
      'Follow-up Log: records all the management of the case (Date, Time, Detail, Person and Status). The follow-up Status updates the case\'s, until reaching Closed.',
      'Attach files: in each case you can upload photos, images and documents (PDF, Word, Excel), up to 50 MB per file — ideal for the claim evidence.',
    ],
  },
  'tareas': {
    titulo: 'Tasks',
    intro: 'The main goal of the Tasks module is for the people at the core of Sales, Marketing and Customer Service to be able to assign and receive task assignments, in order to carry them out and complete them by a specific date. This way the team\'s work is distributed, tracked and nothing is left undone.',
    puntos: [
      'A task is assigned to a person (who carries it out), defined by whoever assigns it.',
      'It handles the required completion date versus the actual date, to measure compliance.',
      'It can notify the responsible person by email when a task is assigned to them.',
    ],
    campos: [
      { n: 'Code', d: 'Automatic sequential number of the task.' },
      { n: 'Assignment Date / Time', d: 'When the task was created/assigned.' },
      { n: 'Assigning Person / Executing Person', d: 'Who delegates and who does the work.' },
      { n: 'Description', d: 'What must be done.' },
      { n: 'Required End Date / Actual End Date', d: 'Committed deadline and actual compliance.' },
      { n: 'Status', d: 'Pending, In Progress, Completed.' },
    ],
    notas: [
      'Email notification: when assigning a task, the responsible person can be notified by email.',
      'Follow-up Log: records the progress (Date, Time, Detail, Person and Status); the follow-up Status updates the task\'s.',
      'Attach files: in each task you can upload photos, images and documents (PDF, Word, Excel), up to 50 MB per file.',
    ],
  },
  'dashboard': {
    titulo: 'Indicators Dashboard',
    intro: 'The Dashboard is the business control panel: it brings together the key indicators (KPIs) and the CRM charts on a single screen. IMPORTANT: the indicators begin to display as the areas supply data. Without loaded information the cards appear empty or at zero; as customers, opportunities, quotes, PQRS, etc. are recorded, the charts come to life with real-time data.',
    puntos: [
      'KPI Cards: totals of Companies, Contacts, Opportunities, Projects, Quotes, open PQRS and Products. Each one is clickable and leads directly to its module.',
      'Sales Pipeline: bars by Stage with the amount of each one — shows the commercial funnel and where the deals are stuck.',
      'Projects by Status: compares Approved Amount vs Collected Amount — controls the financial execution.',
      'Quotes by Status: value by state (Draft, Sent, Approved, Rejected, Expired), in Pesos (COP).',
      'PQRS by Type: Requests, Complaints, Claims and Suggestions — measures the customer service load.',
      'Customers by City / by Region and Map of Colombia: geographic distribution of the business in the country.',
    ],
    notas: [
      'They are drawn with real data: each chart is built with the current information. If an area has not yet loaded its data, its card will indicate so (empty or at zero).',
      'Fully customizable: the indicators can be adapted to specific needs, following a meeting where objectives, measurements and targets are defined for the control and optimization of a management area. The charts and what they measure can be created, removed or changed.',
    ],
  },
  'datos-empresa': {
    titulo: 'Company Data',
    intro: 'This is where the Company\'s own data is recorded and updated: identification, contact, legal representative and the LOGO that appears on the login and on the documents. It is a configuration handled ONLY by a user with the Admin Role.',
    campos: [
      { n: 'Name', d: 'Legal name of the company.' },
      { n: 'ID Type / Document No.', d: 'Tax document (RUC/NIT) and its number.' },
      { n: 'Legal Representative', d: 'Name of the company\'s representative.' },
      { n: 'Email / Phone / Mobile / Website', d: 'Contact details of the company.' },
      { n: 'Logo', d: 'Image shown on the login and on the documents (uploaded and automatically resized).' },
      { n: 'Address / City / Country / Postal Code', d: 'Location of the company.' },
      { n: 'Status', d: 'Active / Inactive.' },
    ],
    notas: [
      'ADMIN ROLE ONLY: this configuration is managed exclusively by a user with the Admin Role.',
      'The logo loaded here is the one everyone sees on the login screen.',
    ],
  },
  'usuarios-claves': {
    titulo: 'Users and Passwords',
    intro: 'Module where the system Users and their access Passwords are created and managed. Each team member who is going to use the CRM has their own user with a secure password. ONLY a user with the Admin Role can manage it.',
    campos: [
      { n: 'First Name / Last Name', d: 'The user\'s data.' },
      { n: 'Username', d: 'Access name (login).' },
      { n: 'Password', d: 'Access password; stored encrypted, never in plain text.' },
      { n: 'Email', d: 'The user\'s email.' },
      { n: 'Role', d: 'Profile that defines their permissions (Admin, Sales, Support, Management…).' },
      { n: 'Status', d: 'Active / Inactive: enables or blocks the user\'s access.' },
    ],
    notas: [
      'Security: passwords are stored encrypted and the login is validated on the server.',
      'ADMIN ROLE ONLY: creating, editing or deactivating users and changing passwords is exclusive to the Admin Role.',
    ],
  },
  'roles': {
    titulo: 'Roles',
    intro: 'Roles define WHAT each user can do in the system. Each role has permissions by module (Read, Create, Edit, Delete), so that each person sees and does only what corresponds to them. They are managed within the Users module (Roles tab) and ONLY by a user with the Admin Role.',
    puntos: [
      'Default roles: Admin (full access), Sales, Support and Management — and new ones can be created.',
      'Each role defines permissions by module: Read, Create, Edit and Delete.',
      'When assigning a role to a user, they automatically inherit those permissions.',
    ],
    campos: [
      { n: 'Role Name', d: 'Identifies the profile (e.g. Sales, Support).' },
      { n: 'Permissions by Module', d: 'Read / Create / Edit / Delete in each CRM module.' },
    ],
    notas: [
      'ADMIN ROLE ONLY: the creation and editing of roles and permissions is exclusive to the Admin Role.',
    ],
  },
  'referencias': {
    titulo: 'References',
    intro: 'The References module is dedicated to storing the data used in other modules to populate their options — for example Payment Terms, ID Type, Currency Type, Customer Activity, etc. They are the basis of information consistency, and can only be updated and managed by the system Administrator.',
    puntos: [
      'What you change here automatically appears in the dropdowns of the modules.',
      'Each value can be added, edited or activated/deactivated (without deleting the history).',
      'Well configured, they prevent everyone from writing differently and keep the information clean and organized.',
    ],
    campos: [
      { n: 'Description', d: 'The value/option that will be shown in the dropdown of the corresponding module. (It is the field common to ALL tables.)' },
      { n: 'Status', d: 'Active / Inactive: enables or disables the option without deleting it.' },
    ],
    notas: [
      'What each group of tables feeds: Commercial (ID Type, Currency Type, Payment Terms, Tax %) · Activities (of Company/Customer and of Supplier) · States/Status (Company, Contact, Opportunity, Quote, Prospect, Project, Supplier and PQRS) · Sales (Opportunity Stage and Origin, Salespeople) · Products (Category and Unit of Measure) · Contacts (Level of Influence) · PQRS (Type and Priority) · Prospects (Origin) · Location (Country and City) · Security (Roles). All share the same fields: Description and Status.',
      'IMPORTANT: only the system Administrator can update and manage these tables, due to their impact on the entire system.',
    ],
  },
  'factores-monedas': {
    titulo: 'Currency Conversion Factors',
    intro: 'Records the factors to convert between currencies, used in the system calculations (for example, to show equivalent amounts in another currency).',
    campos: [
      { n: 'No. / Registration Date', d: 'Automatic sequential number (FCM-XXXXX) and current date.' },
      { n: 'Pesos to US$ Factor', d: 'How many pesos equal one dollar (e.g. 4000).' },
      { n: 'US$ to Euro Factor', d: 'How many euros one dollar equals (e.g. 0.92).' },
      { n: 'Status', d: 'Active / Inactive.' },
    ],
    notas: [
      'Configuration normally managed by the system Administrator.',
    ],
  },
}
