import { type CapituloObra } from './store/capitulos-obra-store'

export const SEED_CAPITULOS: Omit<CapituloObra, 'pais'>[] = [
  {
    "id": "cap-pr2-01",
    "codigo": "E-01",
    "nombre": "ESTUDIOS, DISEÑOS, LICENCIAS Y PÓLIZAS",
    "tipo": "Indirecto",
    "orden": 1,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:00:00.000Z"
  },
  {
    "id": "cap-pr2-02",
    "codigo": "E-02",
    "nombre": "OBRAS PRELIMINARES Y LIMPIEZA DEL TERRENO",
    "tipo": "Indirecto",
    "orden": 2,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:01:00.000Z"
  },
  {
    "id": "cap-pr2-03",
    "codigo": "E-03",
    "nombre": "MOVIMIENTO DE TIERRAS Y EXCAVACIÓN",
    "tipo": "Directo",
    "orden": 3,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:02:00.000Z"
  },
  {
    "id": "cap-pr2-04",
    "codigo": "E-04",
    "nombre": "CIMENTACIÓN Y CONTENCIÓN",
    "tipo": "Directo",
    "orden": 4,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:03:00.000Z"
  },
  {
    "id": "cap-pr2-05",
    "codigo": "E-05",
    "nombre": "ESTRUCTURA EN CONCRETO",
    "tipo": "Directo",
    "orden": 5,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:04:00.000Z"
  },
  {
    "id": "cap-pr2-06",
    "codigo": "E-06",
    "nombre": "MAMPOSTERÍA Y CERRAMIENTOS",
    "tipo": "Directo",
    "orden": 6,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:05:00.000Z"
  },
  {
    "id": "cap-pr2-07",
    "codigo": "E-07",
    "nombre": "PAÑETES, REVOQUES Y CIELOS RASOS",
    "tipo": "Directo",
    "orden": 7,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:06:00.000Z"
  },
  {
    "id": "cap-pr2-08",
    "codigo": "E-08",
    "nombre": "INSTALACIONES HIDROSANITARIAS",
    "tipo": "Directo",
    "orden": 8,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:07:00.000Z"
  },
  {
    "id": "cap-pr2-09",
    "codigo": "E-09",
    "nombre": "RED DE GAS DOMICILIARIO",
    "tipo": "Directo",
    "orden": 9,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:08:00.000Z"
  },
  {
    "id": "cap-pr2-10",
    "codigo": "E-10",
    "nombre": "INSTALACIONES ELÉCTRICAS",
    "tipo": "Directo",
    "orden": 10,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:09:00.000Z"
  },
  {
    "id": "cap-pr2-11",
    "codigo": "E-11",
    "nombre": "CORRIENTES DÉBILES: CITOFONÍA, CCTV Y DATOS",
    "tipo": "Directo",
    "orden": 11,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:10:00.000Z"
  },
  {
    "id": "cap-pr2-12",
    "codigo": "E-12",
    "nombre": "VENTILACIÓN MECÁNICA Y EXTRACCIÓN",
    "tipo": "Directo",
    "orden": 12,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:11:00.000Z"
  },
  {
    "id": "cap-pr2-13",
    "codigo": "E-13",
    "nombre": "EQUIPOS HIDRÁULICOS: BOMBEO, TANQUES Y PRESIÓN",
    "tipo": "Directo",
    "orden": 13,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:12:00.000Z"
  },
  {
    "id": "cap-pr2-14",
    "codigo": "E-14",
    "nombre": "ACABADOS (PISOS, ENCHAPES Y PINTURA)",
    "tipo": "Directo",
    "orden": 14,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:13:00.000Z"
  },
  {
    "id": "cap-pr2-15",
    "codigo": "E-15",
    "nombre": "CARPINTERÍA, VENTANERÍA Y CUBIERTA",
    "tipo": "Directo",
    "orden": 15,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:14:00.000Z"
  },
  {
    "id": "cap-pr2-16",
    "codigo": "E-16",
    "nombre": "MUEBLES FIJOS: COCINAS INTEGRALES Y CLOSETS",
    "tipo": "Directo",
    "orden": 16,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:15:00.000Z"
  },
  {
    "id": "cap-pr2-17",
    "codigo": "E-17",
    "nombre": "URBANISMO, EXTERIORES Y PAISAJISMO",
    "tipo": "Directo",
    "orden": 17,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:16:00.000Z"
  },
  {
    "id": "cap-pr2-18",
    "codigo": "E-18",
    "nombre": "SEGURIDAD INDUSTRIAL (SST), ANDAMIOS Y EQUIPOS DE ALTURA",
    "tipo": "Indirecto",
    "orden": 18,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:17:00.000Z"
  },
  {
    "id": "cap-pr2-19",
    "codigo": "E-19",
    "nombre": "ASEO GENERAL, RESANE Y ENTREGA",
    "tipo": "Directo",
    "orden": 19,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:18:00.000Z"
  },
  {
    "id": "cap-pr2-20",
    "codigo": "E-20",
    "nombre": "MOVILIZACIÓN, TRANSPORTE Y VIAJES",
    "tipo": "Indirecto",
    "orden": 20,
    "situacion": "Activo",
    "oferta_consecutivo": "PR-00002",
    "cliente": "Inmobiliaria Nuevo Horizonte E.I.R.L.",
    "codigo_gtm": "GTM-OF-00002",
    "responsable_tecnico": "Juan Andres Arango",
    "comercial": "Karina Cardona",
    "lugar_ejecucion": "Lima",
    "moneda": "Soles",
    "alcance": "Obra nueva llave en mano: desde estudios, diseños y licencias hasta acabados, urbanismo y entrega. Edificio multifamiliar de 5 pisos, 40 apartamentos.",
    "fecha_registro": "2026-08-27",
    "creado_por": "Administrador Contable",
    "creado_en": "2026-08-27T09:19:00.000Z"
  }
]
