// Datos demo del edificio PR-00002 (traídos de crmgtm). País Colombia.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const SEED_PRESUPUESTO_SUBCONTRATISTAS: any[] = [
  {
    "id": "be0aea83-0919-47a8-973b-db7a70bd3746",
    "codigo": "PS-00001",
    "subcontratista": "Ingeniería y Estudios del Pacífico S.A.C.",
    "proyecto": "Edificio Multifamiliar",
    "capitulo": "E-01 · ESTUDIOS, DISEÑOS, LICENCIAS Y PÓLIZAS",
    "descripcion": "Presupuesto presentado por el subcontratista para el proyecto Edificio Multifamiliar.",
    "responsable": "Ing. Andrés Quispe",
    "monto": 139216,
    "moneda": "Soles",
    "fecha_emision": "2026-08-25",
    "observaciones": "",
    "pais": "Colombia",
    "situacion": "Recibido",
    "creado_por_usuario": "Jose E Palomares",
    "creado_en": "2026-08-30T12:00:00.000Z",
    "fecha_registro": "2026-08-30"
  },
  {
    "id": "54f00f5d-260d-4bd1-8caa-3c55953213a2",
    "codigo": "PS-00002",
    "subcontratista": "Redes y Gas Perú S.A.C.",
    "proyecto": "Edificio Multifamiliar",
    "capitulo": "Varios (2 capítulos)",
    "descripcion": "Presupuesto presentado por el subcontratista para el proyecto Edificio Multifamiliar.",
    "responsable": "Ing. Carla Rojas",
    "monto": 91168,
    "moneda": "Soles",
    "fecha_emision": "2026-08-25",
    "observaciones": "",
    "pais": "Colombia",
    "situacion": "Recibido",
    "creado_por_usuario": "Jose E Palomares",
    "creado_en": "2026-08-30T12:00:00.000Z",
    "fecha_registro": "2026-08-30"
  },
  {
    "id": "0d5bc423-bc25-4ed2-95e6-0c9c1403eba5",
    "codigo": "PS-00003",
    "subcontratista": "Sistemas Electrónicos y Ventilación S.A.C.",
    "proyecto": "Edificio Multifamiliar",
    "capitulo": "Varios (2 capítulos)",
    "descripcion": "Presupuesto presentado por el subcontratista para el proyecto Edificio Multifamiliar.",
    "responsable": "Ing. Diego Salazar",
    "monto": 278432,
    "moneda": "Soles",
    "fecha_emision": "2026-08-25",
    "observaciones": "",
    "pais": "Colombia",
    "situacion": "Recibido",
    "creado_por_usuario": "Jose E Palomares",
    "creado_en": "2026-08-30T12:00:00.000Z",
    "fecha_registro": "2026-08-30"
  },
  {
    "id": "73b9b11a-24c5-49a0-bf2f-55883d52db82",
    "codigo": "PS-00004",
    "subcontratista": "HidroAscensores Andinos S.A.C.",
    "proyecto": "Edificio Multifamiliar",
    "capitulo": "Varios (2 capítulos)",
    "descripcion": "Presupuesto presentado por el subcontratista para el proyecto Edificio Multifamiliar.",
    "responsable": "Ing. Marta León",
    "monto": 551936,
    "moneda": "Soles",
    "fecha_emision": "2026-08-25",
    "observaciones": "",
    "pais": "Colombia",
    "situacion": "Recibido",
    "creado_por_usuario": "Jose E Palomares",
    "creado_en": "2026-08-30T12:00:00.000Z",
    "fecha_registro": "2026-08-30"
  },
  {
    "id": "7a2cbd93-15c2-4ad0-9ae1-66ed9108aa7c",
    "codigo": "PS-00005",
    "subcontratista": "Fachadas, Cocinas y Acabados S.A.C.",
    "proyecto": "Edificio Multifamiliar",
    "capitulo": "Varios (3 capítulos)",
    "descripcion": "Presupuesto presentado por el subcontratista para el proyecto Edificio Multifamiliar.",
    "responsable": "Arq. Felipe Chávez",
    "monto": 825286,
    "moneda": "Soles",
    "fecha_emision": "2026-08-25",
    "observaciones": "",
    "pais": "Colombia",
    "situacion": "Recibido",
    "creado_por_usuario": "Jose E Palomares",
    "creado_en": "2026-08-30T12:00:00.000Z",
    "fecha_registro": "2026-08-30"
  }
]
