// Datos demo del edificio PR-00002 (traídos de crmgtm). País Colombia.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const SEED_PRODUCTOS_VARIOS: any[] = [
  {
    "id": "prodvar-0001",
    "codigo": "MAT-0001",
    "descripcion": "Cerramiento provisional en tela verde + postes",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "ml",
    "costo_unitario": 38.4,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0002",
    "codigo": "MAT-0002",
    "descripcion": "Caseta / almacén provisional de obra",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "gl",
    "costo_unitario": 10030,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0003",
    "codigo": "MAT-0003",
    "descripcion": "Alquiler volqueta retiro de material (viaje)",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "vje",
    "costo_unitario": 212.4,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0004",
    "codigo": "MAT-0004",
    "descripcion": "Concreto premezclado 3.000 psi",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "m³",
    "costo_unitario": 624,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0005",
    "codigo": "MAT-0005",
    "descripcion": "Acero de refuerzo 60.000 psi",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "kg",
    "costo_unitario": 6.14,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0006",
    "codigo": "MAT-0006",
    "descripcion": "Malla electrosoldada",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "m²",
    "costo_unitario": 21.6,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0007",
    "codigo": "MAT-0007",
    "descripcion": "Concreto premezclado 4.000 psi",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "m³",
    "costo_unitario": 672,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0008",
    "codigo": "MAT-0008",
    "descripcion": "Acero de refuerzo figurado",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "kg",
    "costo_unitario": 6.25,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0009",
    "codigo": "MAT-0009",
    "descripcion": "Formaleta metálica (alquiler m²-mes)",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "m²",
    "costo_unitario": 25.96,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0010",
    "codigo": "MAT-0010",
    "descripcion": "Casetón / aligerante de placa",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "un",
    "costo_unitario": 11.4,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0011",
    "codigo": "MAT-0011",
    "descripcion": "Ladrillo tolete estructural",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "un",
    "costo_unitario": 1.14,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0012",
    "codigo": "MAT-0012",
    "descripcion": "Mortero de pega (cemento + arena)",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "m³",
    "costo_unitario": 408,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0013",
    "codigo": "MAT-0013",
    "descripcion": "Mortero de pañete (cemento + arena)",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "m³",
    "costo_unitario": 408,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0014",
    "codigo": "MAT-0014",
    "descripcion": "Lámina drywall + estructura + masilla",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "m²",
    "costo_unitario": 46.36,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0015",
    "codigo": "MAT-0015",
    "descripcion": "Tubería PVC presión y sanitaria + accesorios",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "gl",
    "costo_unitario": 93600,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0016",
    "codigo": "MAT-0016",
    "descripcion": "Aparatos sanitarios y grifería",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "gl",
    "costo_unitario": 75640,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0017",
    "codigo": "MAT-0017",
    "descripcion": "Tubería de gas, reguladores y accesorios",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "gl",
    "costo_unitario": 55200,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0018",
    "codigo": "MAT-0018",
    "descripcion": "Cableado, tubería EMT y accesorios",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "gl",
    "costo_unitario": 114000,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0019",
    "codigo": "MAT-0019",
    "descripcion": "Tableros, protecciones y salidas",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "gl",
    "costo_unitario": 58560,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0020",
    "codigo": "MAT-0020",
    "descripcion": "Ductos, rejillas y accesorios",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "gl",
    "costo_unitario": 28800,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0021",
    "codigo": "MAT-0021",
    "descripcion": "Tanques de almacenamiento de agua potable",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "un",
    "costo_unitario": 21600,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0022",
    "codigo": "MAT-0022",
    "descripcion": "Cerámica / porcelanato",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "m²",
    "costo_unitario": 82.96,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0023",
    "codigo": "MAT-0023",
    "descripcion": "Estuco, pintura y vinilos",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "gl",
    "costo_unitario": 51240,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0024",
    "codigo": "MAT-0024",
    "descripcion": "Enchape de baños y cocinas",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "m²",
    "costo_unitario": 67.1,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0025",
    "codigo": "MAT-0025",
    "descripcion": "Puertas y carpintería en madera",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "un",
    "costo_unitario": 585.6,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0026",
    "codigo": "MAT-0026",
    "descripcion": "Ventanería en aluminio + vidrio",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "m²",
    "costo_unitario": 237.9,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0027",
    "codigo": "MAT-0027",
    "descripcion": "Impermeabilización y cubierta",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "m²",
    "costo_unitario": 102,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0028",
    "codigo": "MAT-0028",
    "descripcion": "Concreto para andenes y sardineles",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "m³",
    "costo_unitario": 624,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0029",
    "codigo": "MAT-0029",
    "descripcion": "Adoquín, grama y jardinería",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "m²",
    "costo_unitario": 75.64,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0030",
    "codigo": "MAT-0030",
    "descripcion": "Dotación, EPP y señalización de obra",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "gl",
    "costo_unitario": 38400,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  },
  {
    "id": "prodvar-0031",
    "codigo": "MAT-0031",
    "descripcion": "Insumos de aseo, resane y protección",
    "categoria": "",
    "grupo": "",
    "sub_grupo": "",
    "unidad_medida": "gl",
    "costo_unitario": 16800,
    "pais": "Colombia",
    "situacion": "Activo",
    "creado_por_usuario": "Administrador Contable",
    "creado_en": "2026-08-29T09:00:00.000Z",
    "fecha_registro": "2026-08-29"
  }
]
